# vi: set ft=ruby :

machines = 2

Vagrant.configure("2") do |config|

  config.vm.define "haproxyServer" do |haproxyServer|
    haproxyServer.vm.box = "bento/ubuntu-18.04"
    haproxyServer.vm.hostname = "haproxyServer"
    haproxyServer.vm.network :private_network, ip: "192.168.100.5"
    haproxyServer.vm.network "forwarded_port", guest: 80, host: 3000
    haproxyServer.vm.network "forwarded_port", guest: 8404, host: 8404
    haproxyServer.vm.provision "shell", path: "script.sh"

  end

  machines.times do |i|
    config.vm.define "webi#{i+1}" do |webi|
      webi.vm.box = "bento/ubuntu-18.04"
      webi.vm.hostname = "webi-#{i+1}"
      webi.vm.network :private_network, ip: "192.168.100.#{10+i+1}"
      webi.vm.provision "shell", path: "bootstrap.sh"

    end
  end
end